version: '3.8'
services:
  frontend:
    build:
      context: ./Croma-PS
      dockerfile: Dockerfile 
    ports:
      - "5173:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    env_file:
      - .env
    depends_on:
      - model  

  model:
    build:
      context: ./model  
      dockerfile: Dockerfile

networks:
  default:
    driver: bridge
